require:
  - rubocop-capybara
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "config/puma.rb"
    - "config/initializers/filter_parameter_logging.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"

RSpec/MultipleExpectations:
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

Style/NumericLiterals:
  Exclude:
    - "db/schema.rb"

Style/BlockComments:
  Exclude:
    - "spec/spec_helper.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false # enable once we have locales configured

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - happy path

RSpec/ExampleLength:
  Max: 10
