name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/etikedo_test

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Not needed with a .ruby-version file
          # ruby-version: 3.2.1
          # runs 'bundle install' and caches installed gems automatically
          bundler-cache: true

      - name: Create DB
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:prepare

      - name: Check PostgreSQL connection
        run: |
          PGPASSWORD=postgres psql -h localhost -U postgres -d etikedo_test -c 'SELECT 1;'

      - name: Run tests
        run: |
          bundle exec rspec

      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
